#!/bin/bash

# 🔐 GUIA DEFINITIVO: Como Obter String de Conexão Correta do Supabase

echo "========================================================================"
echo "🔐 GUIA: Como Obter Connection String Correta do Supabase"
echo "========================================================================"
echo ""
echo "O erro 'Tenant or user not found' indica que:"
echo "  1. Projeto pode estar PAUSADO"
echo "  2. Credenciais podem estar incorretas"
echo "  3. String de conexão pode estar no formato errado"
echo ""
echo "========================================================================"
echo "📋 PASSO A PASSO PARA RESOLVER:"
echo "========================================================================"
echo ""

echo "1️⃣ ACESSE O SUPABASE DASHBOARD"
echo "   Link direto: https://app.supabase.com/project/vfhzimozqsbdqknkncny"
echo ""

echo "2️⃣ VERIFIQUE SE O PROJETO ESTÁ ATIVO"
echo "   ❌ Se ver mensagem 'Project paused' ou 'Inactive'"
echo "   ✅ Clique em 'Resume project' ou 'Restore project'"
echo "   ⏳ Aguarde 2-3 minutos"
echo ""

echo "3️⃣ OBTER CONNECTION STRING CORRETA"
echo "   📍 No dashboard, vá em:"
echo "      Settings → Database"
echo ""
echo "   📋 Role até 'Connection string'"
echo "   📋 Selecione 'URI' (não 'Connection parameters')"
echo "   📋 Mode: Selecione 'Session' (recomendado para Chatwoot)"
echo ""
echo "   📝 A string deve estar no formato:"
echo "      postgresql://postgres.vfhzimozqsbdqknkncny:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
echo ""
echo "   ⚠️  COPIE EXATAMENTE como aparece no dashboard!"
echo ""

echo "4️⃣ VERIFICAR SENHA DO DATABASE"
echo "   📍 Ainda em Settings → Database"
echo "   📋 Role até 'Database password'"
echo ""
echo "   🔑 Senhas tentadas:"
echo "      ❌ TqgcYbFD5EKGAQuo (antiga - não funcionou)"
echo "      ❌ fh8eIGFps5xpVE0g (nova - não funcionou)"
echo ""
echo "   💡 OPÇÕES:"
echo "      A) Copie a senha atual exibida no dashboard"
echo "      B) OU clique em 'Reset database password'"
echo "         - Copie a NOVA senha (só aparece uma vez!)"
echo "         - Anote em local seguro"
echo ""

echo "5️⃣ TESTAR CONEXÃO MANUALMENTE"
echo "   Execute este comando substituindo [PASSWORD]:"
echo ""
echo "   docker run --rm postgres:15-alpine psql \\"
echo '     "postgresql://postgres.vfhzimozqsbdqknkncny:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require" \'
echo '     -c "SELECT version();"'
echo ""

echo "========================================================================"
echo "🎯 FORMATOS DE CONNECTION STRING VÁLIDOS:"
echo "========================================================================"
echo ""

echo "📍 OPÇÃO 1: Session Mode (RECOMENDADO)"
echo "postgresql://postgres.vfhzimozqsbdqknkncny:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require&prepared_statements=false"
echo ""

echo "📍 OPÇÃO 2: Transaction Mode"
echo "postgresql://postgres.vfhzimozqsbdqknkncny:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepared_statements=false"
echo ""

echo "📍 OPÇÃO 3: Conexão Direta (sem pooler)"
echo "postgresql://postgres:[PASSWORD]@db.vfhzimozqsbdqknkncny.supabase.co:5432/postgres?sslmode=require&prepared_statements=false"
echo ""

echo "⚠️  Substitua [PASSWORD] pela senha CORRETA do dashboard!"
echo ""

echo "========================================================================"
echo "🆘 CHECKLIST DE VERIFICAÇÃO NO SUPABASE:"
echo "========================================================================"
echo ""
echo "  [ ] Projeto está ATIVO (não pausado)"
echo "  [ ] Database password está correta"
echo "  [ ] Connection string copiada do dashboard"
echo "  [ ] SSL está habilitado (sslmode=require)"
echo "  [ ] Região está correta (sa-east-1)"
echo "  [ ] Porta está correta (5432 ou 6543)"
echo ""

echo "========================================================================"
echo "📞 INFORMAÇÕES DO SEU PROJETO:"
echo "========================================================================"
echo ""
echo "Project Reference: vfhzimozqsbdqknkncny"
echo "Project URL: https://vfhzimozqsbdqknkncny.supabase.co"
echo "Dashboard: https://app.supabase.com/project/vfhzimozqsbdqknkncny"
echo "Região Esperada: sa-east-1 (São Paulo, AWS)"
echo ""

echo "========================================================================"
echo "🎯 PRÓXIMOS PASSOS:"
echo "========================================================================"
echo ""
echo "1. Acesse o dashboard do Supabase (link acima)"
echo "2. Verifique se o projeto está ativo"
echo "3. Copie a connection string EXATA do dashboard"
echo "4. Anote a senha do database"
echo "5. Me envie:"
echo "   - Status do projeto (ativo/pausado)"
echo "   - Connection string completa do dashboard"
echo "   - Senha do database"
echo ""
echo "💡 Com essas informações corretas, conseguiremos fazer funcionar!"
echo ""
echo "========================================================================"